/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2025-04-25 07:37:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.util.*;
import com.web12.util.MyDataBase;
import com.web12.model.Bbs05Dto;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(5);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.web12.model.Bbs05Dto");
    _jspx_imports_classes.add("com.web12.util.MyDataBase");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/base.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	margin: 10px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table, table tr>th, table tr>td {\r\n");
      out.write("	border: 1px solid gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr {}\r\n");
      out.write("\r\n");
      out.write("table tr>th:nth-child(1) {\r\n");
      out.write("	width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>th:nth-child(3) {\r\n");
      out.write("	width: 120px;\r\n");
      out.write("}\r\n");
      out.write("table tr>th:nth-child(4) {\r\n");
      out.write("	width: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>th {\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>td {\r\n");
      out.write("	height: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>td:nth-child(1),\r\n");
      out.write("table tr>td:nth-child(3),\r\n");
      out.write("table tr>td:nth-child(4) {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>td:nth-child(2) {\r\n");
      out.write("	padding: 0px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr>td>a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: gray;\r\n");
      out.write("	line-height: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table tr:hover>td {\r\n");
      out.write("	background-color: yellow;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table+p {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table+p>a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("	border-right: 3px solid #333333;\r\n");
      out.write("	border-bottom: 3px solid #333333;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String sql = "select * from bbs05 order by num desc";
	List<Bbs05Dto> list = new ArrayList<>();
	Statement stmt = null;
	ResultSet rs = null;
	try {
		stmt = MyDataBase.getConnection().createStatement();
		rs = stmt.executeQuery(sql);
		while (rs.next()) {
			list.add(new Bbs05Dto(
						rs.getInt("num"),
						rs.getString("sub"),
						rs.getString("content"),
						rs.getInt("cnt"),
						rs.getDate("nalja")
					));
		}
	} finally {
		if (MyDataBase.getConnection() != null) MyDataBase.getConnection().close();
	}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div>\r\n");
      out.write("		<div id=\"header\">\r\n");
      out.write("			<h1>한국it여성기업인협회</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"menu\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"../\">home</a></li>\r\n");
      out.write("				<li><a href=\"../intro.jsp\">intro</a></li>\r\n");
      out.write("				<li><a href=\"./\">bbs</a></li>\r\n");
      out.write("				<li><a href=\"../login/\">login</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("		<!-- content begin -->\r\n");
      out.write("			<h2>리스트 페이지</h2>\r\n");
      out.write("			<table>\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>no</th>\r\n");
      out.write("						<th>subject</th>\r\n");
      out.write("						<th>nalja</th>\r\n");
      out.write("						<th>cnt</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				<tbody>\r\n");
      out.write("					");

						for (Bbs05Dto bean : list) { 
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td><a href=\"detail.jsp?num=");
      out.print(bean.getNum() );
      out.write('"');
      out.write('>');
      out.print(bean.getNum() );
      out.write("</a></td>\r\n");
      out.write("						<td><a href=\"detail.jsp?num=");
      out.print(bean.getNum() );
      out.write('"');
      out.write('>');
      out.print(bean.getSub() );
      out.write("</a></td>\r\n");
      out.write("						<td><a href=\"detail.jsp?num=");
      out.print(bean.getNum() );
      out.write('"');
      out.write('>');
      out.print(bean.getNalja() );
      out.write("</a></td>\r\n");
      out.write("						<td><a href=\"detail.jsp?num=");
      out.print(bean.getNum() );
      out.write('"');
      out.write('>');
      out.print(bean.getCnt() );
      out.write("</a></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

						}
					
      out.write("\r\n");
      out.write("				</tbody>\r\n");
      out.write("			</table>\r\n");
      out.write("			<p><a href=\"add.jsp\">입력</a></p>\r\n");
      out.write("		<!-- content end -->\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"footer\">\r\n");
      out.write("			<address>(06130) 서울 강남구 테헤란로 7길 22, 한국과학기술회관 1관 303호</address>\r\n");
      out.write("			<p>&copy;한국IT여성기업인협회 Inc. All Rights Reserved.</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
