eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${zone}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
      - id: controld
        uri: lb://CONTROLD
        predicates:
        - Path=/api/**  
      - id: fe
        uri: http://fe:3000
        predicates:
        - Path=/**
          