spring:
  application:
    name: gateway01
#   cloud:
#     gateway:
#       routes:
#         - id: user01
#           uri: http://localhost:8092
#           predicates:
#             - Path=/api/user/**
#         - id: dept01
#           uri: http://localhost:8091
#           predicates:
#             - Path=/api/dept/**
#         - id: react01
#           uri: http://localhost:3000
#           predicates:
#             - Path=/**

server:
  port: 8080
