CREATE TABLE BBS05 
(
  NUM NUMBER NOT NULL 
, SUB VARCHAR2(20) 
, CONTENT VARCHAR2(2000) 
, CNT NUMBER DEFAULT 0 
, NALJA DATE DEFAULT sysdate 
, CONSTRAINT BBS05_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);
CREATE SEQUENCE BBS05_SEQ;
