services:
  # py04:
  #   image: py04
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - net01
  db:
    image: mysql:lts
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: xe
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
    networks:
      - net01

networks:
  net01:
    external: true
