const os = require("os");
// console.log(os);
console.log(os.arch());
// console.log(os.cpus());
console.log(os.cpus().length);
console.log(os.hostname());
console.log(os.platform());
console.log(os.release());
console.log(os.type());
console.log(os.totalmem());
console.log(os.userInfo().homedir);
console.log(os.tmpdir());
