Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20240821.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 7080
  config.vm.network "forwarded_port", guest: 3306, host: 33306

  config.vm.provision "shell", inline: <<-SHELL
    apt update -y
    apt install -y openjdk-8-jdk-headless
    echo export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 >> /etc/profile
    source /etc/profile
    apt install -y tomcat9
  SHELL
end
