CREATE TABLE `bbs05` (
	`num` INT NOT NULL AUTO_INCREMENT,
	`sub` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`content` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`cnt` INT NULL DEFAULT NULL,
	`nalja` TIMESTAMP NULL DEFAULT (NOW()),
	PRIMARY KEY (`num`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
