/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.100
 * Generated at: 2025-05-03 08:51:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.mvc.model.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.mvc.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>📋 JSP 게시판</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #f7f9fc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	max-width: 900px;\r\n");
      out.write("	margin: 40px auto;\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th, td {\r\n");
      out.write("	padding: 14px 10px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("	background-color: #4a90e2;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("	background-color: #f1f5fa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr:hover {\r\n");
      out.write("	background-color: #e1ecf7;\r\n");
      out.write("	transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".write-btn, .search-box {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".write-btn a {\r\n");
      out.write("	background-color: #4a90e2;\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 10px 18px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a {\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	background-color: #eee;\r\n");
      out.write("	color: #333;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a.active {\r\n");
      out.write("	background-color: #4a90e2;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination .arrow {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination a.arrow:hover {\r\n");
      out.write("	background-color: #4a90e2;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box input[type=\"text\"] {\r\n");
      out.write("	padding: 8px;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-box input[type=\"submit\"] {\r\n");
      out.write("	padding: 8px 12px;\r\n");
      out.write("	background-color: #4a90e2;\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 4px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h2>📋 JSP 게시판</h2>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"search-box\">\r\n");
      out.write("			<!-- 검색 폼 -->\r\n");
      out.write("			<form method=\"get\" action=\"");
      out.print(request.getContextPath());
      out.write("/list\">\r\n");
      out.write("				<input type=\"text\" name=\"keyword\"\r\n");
      out.write("					value=\"");
      out.print(request.getAttribute("keyword") != null ? request.getAttribute("keyword") : "");
      out.write("\"\r\n");
      out.write("					placeholder=\"검색어 입력\"> <input type=\"submit\" value=\"검색\">\r\n");
      out.write("			</form>\r\n");
      out.write("			<div class=\"write-btn\">\r\n");
      out.write("				<a href=\"write.jsp\">✏️ 글쓰기</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<table>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<th>번호</th>\r\n");
      out.write("				<th>제목</th>\r\n");
      out.write("				<th>작성자</th>\r\n");
      out.write("				<th>작성일</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				List<BoardDto> boardList = (List<BoardDto>) request.getAttribute("dataList");
				int currentPage = (Integer) request.getAttribute("currentPage");
				int totalPages = (Integer) request.getAttribute("totalPages");
			
      out.write("\r\n");
      out.write("			");

				for (BoardDto board : boardList) {
			
      out.write("\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>");
      out.print(board.getId());
      out.write("</td>\r\n");
      out.write("				<td style=\"text-align: left;\"><a\r\n");
      out.write("					href=\"detail.jsp?id=");
      out.print(board.getId());
      out.write('"');
      out.write('>');
      out.print(board.getTitle());
      out.write("</a></td>\r\n");
      out.write("				<td>");
      out.print(board.getUserId());
      out.write("</td>\r\n");
      out.write("				<td>");
      out.print(board.getCreatedAt());
      out.write("</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"pagination\">\r\n");
      out.write("			");

				int prevPage = currentPage - 1 > 0 ? currentPage - 1 : 1;
				int nextPage = currentPage + 1 <= totalPages ? currentPage + 1 : totalPages;

				int pageGroupSize = 10;
				int startPage = ((currentPage - 1) / pageGroupSize) * pageGroupSize + 1;
				int endPage = Math.min(startPage + pageGroupSize - 1, totalPages);

				int prevGroup = startPage - 1 > 0 ? startPage - 1 : 1;
				int nextGroup = endPage + 1 <= totalPages ? endPage + 1 : totalPages;
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

				if (startPage > 1) {
			
      out.write("\r\n");
      out.write("			<a class=\"arrow\"\r\n");
      out.write("				href=\"?page=");
      out.print(prevGroup);
      out.write("&keyword=");
      out.print(request.getParameter("keyword") != null ? request.getParameter("keyword") : "");
      out.write("\">&lt;</a>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

				for (int i = startPage; i <= endPage; i++) {
					if (i == currentPage) {
			
      out.write("\r\n");
      out.write("			<a class=\"active\"\r\n");
      out.write("				href=\"?page=");
      out.print(i);
      out.write("&keyword=");
      out.print(request.getParameter("keyword") != null ? request.getParameter("keyword") : "");
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("			");

				} else {
			
      out.write("\r\n");
      out.write("			<a\r\n");
      out.write("				href=\"?page=");
      out.print(i);
      out.write("&keyword=");
      out.print(request.getParameter("keyword") != null ? request.getParameter("keyword") : "");
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a>\r\n");
      out.write("			");

				}
				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

				if (endPage < totalPages) {
			
      out.write("\r\n");
      out.write("			<a class=\"arrow\"\r\n");
      out.write("				href=\"?page=");
      out.print(nextGroup);
      out.write("&keyword=");
      out.print(request.getParameter("keyword") != null ? request.getParameter("keyword") : "");
      out.write("\">&gt;</a>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
