server:
  port: 7061

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer.group-id: myGroup
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer