DROP TABLE BBS02;
DROP SEQUENCE BBS02_SEQ;

CREATE TABLE BBS02 
(
  NUM NUMBER NOT NULL 
, ID VARCHAR2(16) NOT NULL 
, NALJA DATE DEFAULT sysdate 
, SUBJECT VARCHAR2(30) NOT NULL 
, CONTENT VARCHAR2(2000) 
, CONSTRAINT BBS02_PK PRIMARY KEY 
  (
    NUM 
  )
  ENABLE 
);

CREATE SEQUENCE BBS02_SEQ;

INSERT INTO BBS02 VALUES (BBS02_SEQ.NEXTVAL, 'tester', SYSDATE, 'test1', 'test');
INSERT INTO BBS02 VALUES (BBS02_SEQ.NEXTVAL, 'tester', SYSDATE, 'test2', 'test');
INSERT INTO BBS02 VALUES (BBS02_SEQ.NEXTVAL, 'tester', SYSDATE, 'test3', 'test');
INSERT INTO BBS02 VALUES (BBS02_SEQ.NEXTVAL, 'tester', SYSDATE, 'test4', 'test');
