version: "3"
services:
  db-write:
    build: 
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'reservation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3321:3306'
    # Where our data will be persisted
    volumes:
      - master:/var/lib/mysql
      - master:/var/lib/mysql-files
    networks:
      - net-mysql
  
  db-read:
    build: 
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'reservation'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3322:3306'
    # Where our data will be persisted
    volumes:
      - slave:/var/lib/mysql
      - slave:/var/lib/mysql-files
    networks:
      - net-mysql
  
# Names our volume
volumes:
  master:
  slave: 

networks: 
  net-mysql:
    driver: bridge